version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-activecampaign
            source /usr/local/share/virtualenvs/tap-activecampaign/bin/activate
            pip install -U 'pip<19.2' setuptools
            pip install .[dev]
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_activecampaign/schemas/*.json
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-activecampaign/bin/activate
            pylint tap_activecampaign -d C,R,W
      - add_ssh_keys

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context:
            - circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build