version: 2
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-activecampaign
            source /usr/local/share/virtualenvs/tap-activecampaign/bin/activate
            pip install -U 'pip<19.2' setuptools
            pip install .[test]
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_activecampaign/schemas/*.json
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-activecampaign/bin/activate
            pylint tap_activecampaign -d C,R,W
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-activecampaign/bin/activate
            pip install coverage
            nosetests --with-coverage --cover-erase --cover-package=tap_activecampaign --cover-html-dir=htmlcov tests/unittests
            coverage html
      - add_ssh_keys
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      - run:
          name: 'Integration Tests'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap=tap-activecampaign tests
      - slack/status:
          channel: 'stitch-tap-tester-tests'
          mentions: "${CIRCLE_USERNAME}"
          fail_only: true
          only_for_branches: master
          failure_message: |
            :red_circle: ${CIRCLE_JOB} failed!
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context:
            - circleci-user
            - tap-tester-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build